# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/david/basys_serial/basys_serial.srcs/sources_1/bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1.xci
# IP: The module: 'block_design_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/david/basys_serial/basys_serial.gen/sources_1/bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/david/basys_serial/basys_serial.gen/sources_1/bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/david/basys_serial/basys_serial.srcs/sources_1/bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1.xci
# IP: The module: 'block_design_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/david/basys_serial/basys_serial.gen/sources_1/bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/david/basys_serial/basys_serial.gen/sources_1/bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
