# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_uart_rx_0_0/block_design_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_uart_rx_0_0 || ORIG_REF_NAME==block_design_uart_rx_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_util_ds_buf_0_1/block_design_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_util_ds_buf_0_1 || ORIG_REF_NAME==block_design_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_c_counter_binary_0_0/block_design_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_c_counter_binary_0_0 || ORIG_REF_NAME==block_design_c_counter_binary_0_0} -quiet] -quiet

# XDC: c:/Users/david/basys_serial/basys_serial.gen/sources_1/bd/block_design/block_design_ooc.xdc
